import 'package:freezed_annotation/freezed_annotation.dart';
import 'stress_models.dart';
import 'wellness_models.dart';

part 'proactive_models.freezed.dart';
part 'proactive_models.g.dart';

/// Trigger for proactive outreach
enum InsightTrigger {
  stressTrendingUp,
  activityGap,
  newCityTravel,
  recoveryOpportunity,
  bookingReminder;

  String get debuggingLabel {
    switch (this) {
      case InsightTrigger.stressTrendingUp:
        return 'High Stress Trend';
      case InsightTrigger.activityGap:
        return 'Activity Gap Alert';
      case InsightTrigger.newCityTravel:
        return 'New City Arrival';
      case InsightTrigger.recoveryOpportunity:
        return 'Recovery Window Found';
      case InsightTrigger.bookingReminder:
        return 'Upcoming Booking';
    }
  }
}

/// Priority level for insights
enum InsightPriority { low, medium, high, critical }

/// A proactive insight generated by ANCHOR
@freezed
abstract class ProactiveInsight with _$ProactiveInsight {
  const factory ProactiveInsight({
    required String id,
    required InsightTrigger trigger,
    required InsightPriority priority,
    required String title,
    required String message,
    required DateTime generatedAt,
    @Default([]) List<String> suggestedActions,
    @Default([]) List<WellnessOption> wellnessOptions,
    @Default(false) bool dismissed,
    @Default(false) bool actedUpon,
  }) = _ProactiveInsight;

  factory ProactiveInsight.fromJson(Map<String, dynamic> json) =>
      _$ProactiveInsightFromJson(json);
}

/// Comprehensive context object for the AI
@freezed
abstract class AnchorContext with _$AnchorContext {
  const factory AnchorContext({
    required StressDetectionResult? stressAnalysis,
    required CalendarData? upcomingSchedule,
    @Default([]) List<WellnessOption> wellnessOptions,
    required HistoricalContext? userPatterns,
    required String userLocation,
    @Default([]) List<String> recentMoods,
  }) = _AnchorContext;

  factory AnchorContext.fromJson(Map<String, dynamic> json) =>
      _$AnchorContextFromJson(json);
}
